on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      env:
        required: true
        type: string


jobs:
  example_job:
    name: Pass input  my-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Faithtosin/honig
          ref: master
          path: honig
      - name: Checkout2
        uses: actions/checkout@v2
        
      - run: echo "${{ inputs.username }} and ${{ inputs.env }}" 
      - run: ls -la && pwd && cd .. && ls -l
        name: Check files in repo
